import type { Metadata } from "next";
import "./globals.css";
import { ReduxProvider } from "@/providers/redux-provider";
import { ThemeProvider } from "@/providers/theme.provider";
import SessionProvider from "@/providers/session-provider";
import { getCurrentSession } from "../lib/auth";
import { Toaster } from "@/components/ui/sonner";
import localFont from "next/font/local";
import { Suspense } from "react";

const inter = localFont({
  src: "../../public/font/Inter-VariableFont_slnt,wght.ttf",
});

export const metadata: Metadata = {
  title: "Mossodor",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getCurrentSession();
  return (
    <html style={{ scrollBehavior: "smooth" }} lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <ReduxProvider>
            <ThemeProvider>
              <Toaster richColors position="bottom-right" />
              <Suspense>{children}</Suspense>
            </ThemeProvider>
          </ReduxProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
